version: '3.3'

services:
  app:
    image: node:18.16-alpine3.18
    restart: unless-stopped
    working_dir: /home/node/app
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/home/node/app
    entrypoint: npm run start:dev

  postgres:
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - dev_data:/var/lib/postgresql/data

volumes:
  dev_data:
