services:
  app:
    image: virtualwolf/powerwall-to-pvoutput-uploader:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.6-alpine3.19
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
